SiSee_forTest/Controllers/CommentRecordsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SiSee_v1.Models;
using SiSee_v1.Models.Repository;

namespace SiSee_v1.Controllers
{
    public class CommentRecordsController : Controller
    {
        private AmazonDB db = new AmazonDB();

        private SpotRepository SpotRepository = new SpotRepository();

        // GET: CommentRecords
        public ActionResult Index()
        {
            var commentRecord = db.CommentRecord.Include(c => c.Spot).Include(c => c.User);
            return View(commentRecord.ToList());
        }

        // GET: CommentRecords/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentRecord commentRecord = db.CommentRecord.Find(id);
            if (commentRecord == null)
            {
                return HttpNotFound();
            }
            return View(commentRecord);
        }

        //自訂新增評論
        [HttpPost]
        public ActionResult CreateCommandRecord(FormCollection data)
        {
            if (string.IsNullOrEmpty(User.Identity.Name))
            {
                return RedirectToAction("Details", "Spots", new { id = data["Spot.spot_ID"] });
            }

            CommentRecord commentRecord = new CommentRecord()
            {
                spot_ID = int.Parse(data["Spot.spot_ID"]),
                comment_context = data["Command"],
                comment_grade = data["Grade"],
                user_ID = int.Parse(User.Identity.Name),
                comment_date = System.DateTime.Now
            };

            //SpotRepository.CreateCommand(commentRecord) 
            //暫先用linq新增
            db.CommentRecord.Add(commentRecord);

            db.SaveChanges();

            return RedirectToAction("Details", "Spots", new { id = data["Spot.spot_ID"] });
        }

        // GET: CommentRecords/CheckCommentRecordsCount
        public int? CheckCommentRecordsCount(int id)
        {
            return SpotRepository.GetSpotCommentRecordsCount(id);
        }

        // GET: CommentRecords/Create
        public ActionResult Create()
        {
            ViewBag.spot_ID = new SelectList(db.Spot, "spot_ID", "spot_name");
            ViewBag.user_ID = new SelectList(db.User, "user_ID", "user_name");
            return View();
        }

        // POST: CommentRecords/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "commentrecord_ID,spot_ID,user_ID,comment_context,comment_grade,comment_date")] CommentRecord commentRecord)
        {
            if (ModelState.IsValid)
            {
                db.CommentRecord.Add(commentRecord);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.spot_ID = new SelectList(db.Spot, "spot_ID", "spot_name", commentRecord.spot_ID);
            ViewBag.user_ID = new SelectList(db.User, "user_ID", "user_name", commentRecord.user_ID);
            return View(commentRecord);
        }

        // GET: CommentRecords/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentRecord commentRecord = db.CommentRecord.Find(id);
            if (commentRecord == null)
            {
                return HttpNotFound();
            }

            Spot spot = db.Spot.Where(s => s.spot_ID == commentRecord.spot_ID).First();
            ViewData["SpotName"] = spot.spot_name;

            ViewBag.spot_ID = new SelectList(db.Spot, "spot_ID", "spot_name", commentRecord.spot_ID);
            ViewBag.user_ID = new SelectList(db.User, "user_ID", "user_name", commentRecord.user_ID);

            return View(commentRecord);
        }

        // POST: CommentRecords/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "commentrecord_ID,spot_ID,user_ID,comment_context,comment_grade,comment_date")] CommentRecord commentRecord)
        {
            var id = User.Identity.Name;

            commentRecord.comment_date = System.DateTime.Now;
            commentRecord.user_ID = int.Parse(id);

            if (ModelState.IsValid)
            {
                db.Entry(commentRecord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyComment", "Users");
            }
            ViewBag.spot_ID = new SelectList(db.Spot, "spot_ID", "spot_name", commentRecord.spot_ID);
            ViewBag.user_ID = new SelectList(db.User, "user_ID", "user_name", commentRecord.user_ID);

            return RedirectToAction("MyComment", "Users");
        }

        // GET: CommentRecords/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentRecord commentRecord = db.CommentRecord.Find(id);
            if (commentRecord == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Details", "Users", id);
        }

        // POST: CommentRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CommentRecord commentRecord = db.CommentRecord.Find(id);
            db.CommentRecord.Remove(commentRecord);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiSee_forTest/Controllers/SpotsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SiSee_v1.Models;
using SiSee_v1.Models.Repository;
using SiSee_v1.Models.ViewModels;

namespace SiSee_v1.Controllers
{
    public class SpotsController : Controller
    {
        private AmazonDB db = new AmazonDB();

        private SpotRepository SpotRepository = new SpotRepository();

        // GET: Spots
        public ActionResult Index(string id)
        {
            string searchName = id;

            List<Spot> spot = SpotRepository.GetAll();

            List<Spot> spotList = new List<Spot>();

            //取得含有搜尋內容的資料
            if (!String.IsNullOrEmpty(searchName))
            {
                ViewData["SearchName"] = searchName;

                List<Spot> spot_name = new List<Spot>();

                if (searchName == "依名稱排列")
                {
                    spot_name = db.Spot.Include(s => s.Area).ToList();
                }
                else
                {
                    spot_name = SpotRepository.GetByName(searchName);
                }

                List<Spot> spot_area = SpotRepository.GetByAreaName(searchName);

                spotList.AddRange(spot_name);

                if (spot_area != null)
                {
                    spotList.AddRange(spot_area);
                }

            }
            else
            {
                //ViewData["SearchName"] = "全部";

                //spotList.AddRange(spot.Take<Spot>(50));

                spotList.AddRange(spot);
            }

            ViewData["TotalCount"] = spotList.Count();

            return View(spotList);
        }

        //判斷景點資料是否為空
        private string SetSpotValueNull(string target)
        {
            if (String.IsNullOrEmpty(target))
                return "未提供";
            return target;
        }

        // GET: Spots/Details/5
        public ActionResult Details(int id)
        {
            Spot spot = db.Spot.Find(id);

            List<CommentRecord> commentRecord = db.CommentRecord.Where(s => s.spot_ID == id).OrderBy(s => s.comment_date).ToList();

            if (spot != null)
            {
                SpotDetail spotDetail = new SpotDetail();

                ViewData["SearchName"] = spot.spot_name;

                spot.spot_add = SetSpotValueNull(spot.spot_add);
                spot.spot_context = SetSpotValueNull(spot.spot_context);
                spot.spot_fee = String.IsNullOrEmpty(spot.spot_fee) ? "免費" : spot.spot_fee;
                spot.spot_optimeS = String.IsNullOrEmpty(spot.spot_optimeS) ? "全天開放" : spot.spot_optimeS;
                spot.spot_tel = SetSpotValueNull(spot.spot_tel);
                spot.spot_score = SpotRepository.GetSpotScore(id);

                spotDetail.Spot = spot;

                spotDetail.CommentRecords = commentRecord;

                //新增瀏覽次數 預設user_ID=1 未登入時
                SearchRecord searchReacord = new SearchRecord()
                {
                    spot_ID = id,
                    search_date = System.DateTime.Now,
                    user_ID = String.IsNullOrEmpty(User.Identity.Name) ? 1 : int.Parse(User.Identity.Name)
                };

                ViewData["SearchCount"] = db.SearchRecord.Where(s => s.Spot.spot_ID == id).Count();


                SpotRepository.CreateSearchReacord(searchReacord);

                return View(spotDetail);

            }
            else
            {
                return HttpNotFound();
            }

        }

        // GET: Spots/Create
        public ActionResult Create()
        {
            Random crandom = new Random(Guid.NewGuid().GetHashCode());

            Random crandomUser = new Random(Guid.NewGuid().GetHashCode());

            for (int i = 0; i < 100; i++)
            {
                int id = crandom.Next(1, 3619);

                int uid = crandomUser.Next(3, 39);

                SearchRecord searchReacord = new SearchRecord()
                {
                    spot_ID = id,
                    search_date = System.DateTime.Now,
                    user_ID = uid
                };

                SpotRepository.CreateSearchReacord(searchReacord);


            }


            ViewBag.area_ID = new SelectList(db.Area, "area_ID", "area_Name");
            return View();
        }

        // POST: Spots/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "spot_ID,area_ID,spot_name,spot_tel,spot_context,spot_optimeS,spot_add,spot_fee,spot_score,spot_other,spot_loaction")] Spot spot)
        {
            if (ModelState.IsValid)
            {
                db.Spot.Add(spot);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.area_ID = new SelectList(db.Area, "area_ID", "area_Name", spot.area_ID);
            return View(spot);
        }

        // GET: Spots/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spot spot = db.Spot.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            ViewBag.area_ID = new SelectList(db.Area, "area_ID", "area_Name", spot.area_ID);
            return View(spot);
        }

        // POST: Spots/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "spot_ID,area_ID,spot_name,spot_tel,spot_context,spot_optimeS,spot_add,spot_fee,spot_score,spot_other,spot_loaction")] Spot spot)
        {
            if (ModelState.IsValid)
            {
                db.Entry(spot).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.area_ID = new SelectList(db.Area, "area_ID", "area_Name", spot.area_ID);
            return View(spot);
        }

        // GET: Spots/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spot spot = db.Spot.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            return View(spot);
        }

        // POST: Spots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Spot spot = db.Spot.Find(id);
            db.Spot.Remove(spot);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Spots/BlogSearch
        [HttpGet, ActionName("SearchBlog")]
        public ActionResult SearchBlog(string searchName)
        {
            ViewData["SearchName"] = searchName;

            return View();
        }

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult PathPlan()
        {
            return View();
        }

    }
}

SiSee_forTest/Views/Spots/Create.cshtml
@model SiSee_v1.Models.Spot

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Spot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.area_ID, "area_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("area_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.area_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_context, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_context, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_context, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_optimeS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_optimeS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_optimeS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_add, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_add, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_add, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_fee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_other, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_other, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_other, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot_loaction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot_loaction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot_loaction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SiSee_forTest/Views/Spots/Delete.cshtml
@model SiSee_v1.Models.Spot

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Spot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.spot_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spot_tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spot_context)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_context)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spot_optimeS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_optimeS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spot_add)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_add)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spot_fee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_fee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spot_score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spot_other)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_other)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spot_loaction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spot_loaction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area.area_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area.area_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SiSee_forTest/Views/Spots/Details.cshtml
@model SiSee_v1.Models.ViewModels.SpotDetail
@{
    ViewBag.Title = "詳細資料";
}
@Scripts.Render("~/Scripts/Detail.js")
@Styles.Render("~/Content/css/Details.css")

<style type="text/css">
    .context {
        color: #565656;
    }
</style>

<div class="Control">
    <input class="SpotName" value=@Html.DisplayFor(model => model.Spot.spot_name) type="hidden" />
    <input class="SpotAddress" value=@Html.DisplayFor(model => model.Spot.spot_add) type="hidden" />
    <input class="SpotID" value=@Html.DisplayFor(model => model.Spot.spot_ID) type="hidden" />
</div>
<div class="background">
    <div>
        <span style="font-size:30px;">
            @Html.DisplayFor(model => model.Spot.spot_name)
        </span>
        | @Html.DisplayNameFor(model => model.Spot.spot_add) :
        <span id="address">@Html.DisplayFor(model => model.Spot.spot_add)</span>
    </div>
    <div style="float:left; width:30%;">
        <div style="font-size:medium;" class="context">
            @Html.DisplayFor(model => model.Spot.Area.area_Name)
            <p />
            @Html.DisplayNameFor(model => model.Spot.spot_optimeS) :
            @Html.DisplayFor(model => model.Spot.spot_optimeS)
            <p />
            @Html.DisplayNameFor(model => model.Spot.spot_fee) :
            @Html.DisplayFor(model => model.Spot.spot_fee)
            <p />
            @Html.DisplayNameFor(model => model.Spot.spot_tel) :
            @Html.DisplayFor(model => model.Spot.spot_tel)
            <p />
            @Html.DisplayNameFor(model => model.Spot.spot_score) :
            <span class="ScoreList">@Html.DisplayFor(model => model.Spot.spot_score)</span>
        </div>
        <p><a href="@Html.Encode(Request.UrlReferrer.ToString())" class="btn btn-warning">上一頁</a></p>
        <p />
        <a href="/Spots/SearchBlog?SearchText=@ViewData["SearchName"]" class="btn btn-warning ">找部落格</a>
        <p />
        <a href="#Comment" class="btn btn-warning CommentRecordButton">評論</a>
        <span class="CommentCount" style="color:#db3a0e;">  </span>則評論
        <p />
        <button type="button" class="btn btn-warning FavoriteRecordButton"><span class="glyphicon glyphicon-heart "></span>收藏</button>
        <span class="FavoriteRecordCount" style="color:#db3a0e;">  </span>人收藏
        <p />
        瀏覽數:
        <span class="SearchCount" style="color:#db3a0e;"> @ViewData["SearchCount"]</span>
        <p />
        <button type="button" class="btn btn-warning PlanButton">加入規劃路線</button>
        <p />
    </div>
    <div style="float:left; width:70%;" class="context">
        <p />
        <h4>
            @Html.DisplayNameFor(model => model.Spot.spot_context) :
        </h4>
        <p />
        @Html.DisplayFor(model => model.Spot.spot_context)
        <div class="contains-white">
            google 地圖
            <div id="map-canvas" style="width:99% ;height:280px;"></div>
        </div>
    </div>
    <span style="font-size:20px;color:#db3a0e;">評論</span>  |  共
    <span class="CommentCount"></span>則

    @foreach (var item in Model.CommentRecords)
    {
        <div class="contains-white">
            <div style="width:20%">
                @Html.HiddenFor(modelItem => item.commentrecord_ID)
                <span class="ScoreList">@Html.DisplayFor(modelItem => item.comment_grade)</span>
                <br />
                <h4>@Html.DisplayFor(modelItem => item.User.user_name)</h4> <strong>覺得:</strong>
                <br />
                @Html.DisplayFor(modelItem => item.comment_context)
            </div>
            <br />
            <p class="text">
                (@Html.DisplayFor(modelItem => item.comment_date))
            </p>
        </div>
    }
    <a name="Comment"></a>
    <br />
    <br />
    <div class="contains-white">
        @using (Html.BeginForm("CreateCommandRecord", "CommentRecords", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.Spot.spot_ID)
            @Html.Hidden("UserID", "1")
            <div>
                <p class="col-lg-12">
                    <span class="col-lg-12 col-sm-2">
                        <strong>
                            我要評分
                        </strong>
                    </span>
                    <input type="hidden" class="Grade text form-control col-lg-12 col-sm-10" name="Grade" value="0" />
                    <div class="col-lg-12">
                        <div class="col-lg-12 col-sm-2 CommentImgdiv">
                            <img src="~/Content/img/star_b.png" class="CommentImg" id="1" title="1分~頗差不推薦" />
                            <img src="~/Content/img/star_b.png" class="CommentImg" id="2" title="2分~勉強還可以" />
                            <img src="~/Content/img/star_b.png" class="CommentImg" id="3" title="3分~普普通通" />
                            <img src="~/Content/img/star_b.png" class="CommentImg" id="4" title="4分~值得推薦" />
                            <img src="~/Content/img/star_b.png" class="CommentImg" id="5" title="5分~此生無憾的好地方" />
                        </div>
                    </div>
                </p>
                <p class="col-lg-12">
                    <span class="col-lg-12 col-sm-2">
                        <strong>
                            你覺得 :
                        </strong>
                    </span>
                    <textarea style="margin:2px;" class="text form-control col-lg-12 col-sm-10" cols="3" name="Command" placeholder="留點評論..."></textarea>
                </p>
                <input type="submit" value="送出" class="btn btn-warning" />
            </div>
        }
    </div>
    <p>
        @*@Html.ActionLink("Edit", "Edit", new { id = Model.Spot.spot_ID }) |*@
        @Html.ActionLink("回到列表", "Index")
    </p>
    <div class="FBCommentt" style="display:block">
        <input class="AreaName" value=@Html.DisplayFor(model => model.Spot.Area.area_Name) type="hidden" />
        <div class=" fb-comments" data-href="" data-width="100%" data-numposts="4"></div>
    </div>
</div>

SiSee_forTest/Views/Spots/PathPlan.cshtml
@{
    ViewBag.Title = "路線規劃";
}
@Scripts.Render("~/Scripts/PathPlan.js")

<div class="background" style="float:left; width:100%;">
    <h2>路線規劃</h2>
    <h3 id="SpotName"></h3>
    <h3 id="msg" style="color:#ff6a00;"></h3>
    <div id="pathContext" class=" contains-white" style="float:left; width: 20%;">
        <p>
            <a href="@Html.Encode(Request.UrlReferrer.ToString())" class="btn btn-warning">上一頁</a>
            <button type="button" onclick="ClearlocalStorage()" class="btn-danger btn ">重新規劃</button>
        </p>
        <div id="pathPnt"></div>
    </div>
    <div id="mapsContain" class="contains-white" style="width:50%; float:left;">
        google 地圖
        <div id="map-canvas" style="width:500px;height:600px;"></div>
    </div>
    <div id="pathContain" class=" contains-white" style="float:left; width: 20%;">
        <div id="directions_panel"></div>
    </div>
</div>

SiSee_forTest/Views/Spots/SearchBlog.cshtml
@Scripts.Render("~/Scripts/SearchBlog.js")

@{
    ViewBag.Title = "SearchBlog";
}

<h2>搜尋部落格</h2>
<div>
    <form action="SearchBlog" method="get">
        <input type="text" class="text text-info" name="SearchText" />
        <button type="submit" class="btn btn-warning ">搜尋</button>
    </form>
    <p><a href="@Html.Encode(Request.UrlReferrer.ToString())" class="btn btn-warning">上一頁</a></p>
</div>

<div class="Context">
    <table class="table " style="background-color:#005bff">
        <tr class="info">
            <th colspan="2">搜尋結果：共<span id="ResultCount"></span>筆，第<span id="ResultPage"></span>頁</th>
        </tr>
    </table>
</div>