SiSee_forTest/Controllers/SpotsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SiSee_v1.Models;
using SiSee_v1.Models.Repository;
using SiSee_v1.Models.ViewModels;

namespace SiSee_v1.Controllers
{
    public class SpotsController : Controller
    {
        private AmazonDB db = new AmazonDB();

        private SpotRepository SpotRepository = new SpotRepository();

        // GET: Spots
        public ActionResult Index(string id)
        {
            string searchName = id;

            List<Spot> spot = SpotRepository.GetAll();

            List<Spot> spotList = new List<Spot>();

            //取得含有搜尋內容的資料
            if (!String.IsNullOrEmpty(searchName))
            {
                ViewData["SearchName"] = searchName;

                List<Spot> spot_name = new List<Spot>();

                if (searchName == "依名稱排列")
                {
                    spot_name = db.Spot.Include(s => s.Area).ToList();
                }
                else
                {
                    spot_name = SpotRepository.GetByName(searchName);
                }

                List<Spot> spot_area = SpotRepository.GetByAreaName(searchName);

                spotList.AddRange(spot_name);

                if (spot_area != null)
                {
                    spotList.AddRange(spot_area);
                }

            }
            else
            {
                //ViewData["SearchName"] = "全部";

                //spotList.AddRange(spot.Take<Spot>(50));

                spotList.AddRange(spot);
            }

            ViewData["TotalCount"] = spotList.Count();

            return View(spotList);
        }

        //判斷景點資料是否為空
        private string SetSpotValueNull(string target)
        {
            if (String.IsNullOrEmpty(target))
                return "未提供";
            return target;
        }

        // GET: Spots/Details/5
        public ActionResult Details(int id)
        {
            Spot spot = db.Spot.Find(id);

            List<CommentRecord> commentRecord = db.CommentRecord.Where(s => s.spot_ID == id).OrderBy(s => s.comment_date).ToList();

            if (spot != null)
            {
                SpotDetail spotDetail = new SpotDetail();

                ViewData["SearchName"] = spot.spot_name;

                spot.spot_add = SetSpotValueNull(spot.spot_add);
                spot.spot_context = SetSpotValueNull(spot.spot_context);
                spot.spot_fee = String.IsNullOrEmpty(spot.spot_fee) ? "免費" : spot.spot_fee;
                spot.spot_optimeS = String.IsNullOrEmpty(spot.spot_optimeS) ? "全天開放" : spot.spot_optimeS;
                spot.spot_tel = SetSpotValueNull(spot.spot_tel);
                spot.spot_score = SpotRepository.GetSpotScore(id);

                spotDetail.Spot = spot;

                spotDetail.CommentRecords = commentRecord;

                //新增瀏覽次數 預設user_ID=1 未登入時
                SearchRecord searchReacord = new SearchRecord()
                {
                    spot_ID = id,
                    search_date = System.DateTime.Now,
                    user_ID = String.IsNullOrEmpty(User.Identity.Name) ? 1 : int.Parse(User.Identity.Name)
                };

                ViewData["SearchCount"] = db.SearchRecord.Where(s => s.Spot.spot_ID == id).Count();


                SpotRepository.CreateSearchReacord(searchReacord);

                return View(spotDetail);

            }
            else
            {
                return HttpNotFound();
            }

        }

        // GET: Spots/Create
        public ActionResult Create()
        {
            Random crandom = new Random(Guid.NewGuid().GetHashCode());

            Random crandomUser = new Random(Guid.NewGuid().GetHashCode());

            for (int i = 0; i < 100; i++)
            {
                int id = crandom.Next(1, 3619);

                int uid = crandomUser.Next(3, 39);

                SearchRecord searchReacord = new SearchRecord()
                {
                    spot_ID = id,
                    search_date = System.DateTime.Now,
                    user_ID = uid
                };

                SpotRepository.CreateSearchReacord(searchReacord);


            }


            ViewBag.area_ID = new SelectList(db.Area, "area_ID", "area_Name");
            return View();
        }

        // POST: Spots/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "spot_ID,area_ID,spot_name,spot_tel,spot_context,spot_optimeS,spot_add,spot_fee,spot_score,spot_other,spot_loaction")] Spot spot)
        {
            if (ModelState.IsValid)
            {
                db.Spot.Add(spot);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.area_ID = new SelectList(db.Area, "area_ID", "area_Name", spot.area_ID);
            return View(spot);
        }

        // GET: Spots/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spot spot = db.Spot.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            ViewBag.area_ID = new SelectList(db.Area, "area_ID", "area_Name", spot.area_ID);
            return View(spot);
        }

        // POST: Spots/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "spot_ID,area_ID,spot_name,spot_tel,spot_context,spot_optimeS,spot_add,spot_fee,spot_score,spot_other,spot_loaction")] Spot spot)
        {
            if (ModelState.IsValid)
            {
                db.Entry(spot).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.area_ID = new SelectList(db.Area, "area_ID", "area_Name", spot.area_ID);
            return View(spot);
        }

        // GET: Spots/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spot spot = db.Spot.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            return View(spot);
        }

        // POST: Spots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Spot spot = db.Spot.Find(id);
            db.Spot.Remove(spot);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Spots/BlogSearch
        [HttpGet, ActionName("SearchBlog")]
        public ActionResult SearchBlog(string searchName)
        {
            ViewData["SearchName"] = searchName;

            return View();
        }

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult PathPlan()
        {
            return View();
        }

    }
}

SiSee_forTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SiSee ASP.NET Application</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css/_layout.css")
    @Scripts.Render("~/Scripts/Share.js")
    @Scripts.Render("~/Scripts/jquery.blockUI.js")
    @Scripts.Render("~/Scripts/fbapiconnect.js")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        /*.SearchText {
            border: 2px solid #456879;
            border-radius: 10px;
            height: 22px;
            width: 230px;
        }*/
    </style>
</head>
<body>
    @Html.Partial("_Navbar")
    <!-- 各自VIEW 內容-->
    <div class="container body-content">
        @RenderBody()
        <hr />

        <!-- Login Dialog-->
        <div class="modal fade" id="LoginDialog" role="dialog">
            <div class="modal-dialog modal-sm">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">歡迎加入...</h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-info" style="text-align:center">SiSee將取得你的基本資料</p>
                        <p class="text-info" style="text-align:center">往後您將可自由修改!</p>
                        <div class="form-group">
                            姓名:<span style="text-align:right" id="FBName"></span>
                        </div>
                        <div class="form-group">
                            email:<span style="text-align:right" id="FBMail"></span>
                        </div>
                        @*<div class="form-group">
                                生日:<span id="FBBirth">@DateTime.Now</span>
                            </div>*@
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default CreateNewUserButton" data-dismiss="modal">繼續</button>
                    </div>
                </div>

            </div>
        </div>

        <footer style="margin-top:50px">
            <p>&copy; @DateTime.Now.ToShortDateString()- KUAS MIS .NET Application</p>
        </footer>
    </div>
</body>
</html>

SiSee_forTest/Views/Shared/_LoginMyPartial.cshtml
@using Microsoft.AspNet.Identity
@if (User.Identity.IsAuthenticated)
{
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-th-large"></span>個人管理 <span class="caret"></span></a>
        <ul class="dropdown-menu" style="background-color:#1D2038">
            <li>@Html.ActionLink("個人資料", "Details", "Users", new { id =User.Identity.Name }, new { @style = "" })</li>
            <li role="separator" class="divider"></li>
            @*<li>@Html.ActionLink("我的景點", "MySpots", "Users", null, new { @style = "" })</li>*@
            <li>@Html.ActionLink("我的評論", "MyComment", "Users", null, new { @style = "" })</li>
            <li>@Html.ActionLink("我的收藏", "MyFavorite", "Users", null, new { @style = "" })</li>
        </ul>
    </li>
}
else
{
        <li>
            <a href="#" class="FBloginbutton"><span class="glyphicon glyphicon-tree-deciduous"></span></a>
        </li>
}

SiSee_forTest/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" id="navbartop">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("SiSee", "Home", "Spots", null, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav " id="navbartopfont">
                <li>@Html.ActionLink("首頁", "Home", "Spots")</li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">景點 <span class="caret"></span></a>
                    <ul class="dropdown-menu" style="background-color:#1D2038">
                        <li>@Html.ActionLink("北部", "Index", "Spots", new { id = "北部" }, new { @style = "" })</li>
                        <li>@Html.ActionLink("中部", "Index", "Spots", new { id = "中部" }, new { @style = "" })</li>
                        <li>@Html.ActionLink("南部", "Index", "Spots", new { id = "南部" }, new { @style = "" })</li>
                        <li>@Html.ActionLink("東部", "Index", "Spots", new { id = "東部" }, new { @style = "" })</li>
                    </ul>
                </li>
                <li>@Html.ActionLink("搜尋", "Index", "Spots")</li>
                <li>@Html.ActionLink("路線規劃", "PathPlan", "Spots")</li>
                @Html.Partial("_LoginMyPartial")
                <li>
                    @using (Html.BeginForm("Index", "Spots", FormMethod.Post, new { @class = "navbar-form", @id = "SearchLayoutForm" }))
                    {
                        <div class="input-group">
                            <input name="id" type="text" class="SearchText form-control" value="@ViewData["SearchName"]" />
                            <div class="input-group-btn">
                                <a onclick="document.getElementById('SearchLayoutForm').submit() " class="SearchButton">
                                    <span class="SearchButton btn glyphicon glyphicon-search" style="font-size:5pt"></span>
                                </a>
                            </div>
                        </div>
                    }
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>